### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by nikkon3** [grip-unina/poi-forensics#2]
Hello, congrats for the work to all you guys! i d like to ask when the **training code** from the "_Audio-Visual Person-of-Interest DeepFake Detection_" paper will be available ?

**Comment by Wertiz** [comment]
We are unsure if we can actually release the code so I can't give and estimate date, sorry

**Comment by nikkon3** [comment]
I'm working on reproducing your results for research purposes, and having access to your code would be a huge help. If it turns out you can't share the actual code, would it be possible to release a simplified or redacted version?

Feel free to reach out to me directly at nick.konstantinou.13@gmail.com. 

Thanks again

**Comment by YasamanAdl94** [comment]
Hello, thank you for this awesome work. I am also trying to reproduce the results on this topic. Is it possible to share the training code? Or any reference to help with the code?

**Comment by ats4869** [comment]
I'm working on reproducing your results for research purposes, and having access to your code would be a huge help. If it turns out you can't share the actual code, would it be possible to release a simplified or redacted version?

Feel free to reach out to me directly at zhangyufei1945@163.com

Thanks again

**Comment by mamarasulovs** [comment]
I'm working on reproducing your results for research purposes, and having access to your code would be a huge help. If it turns out you can't share the actual code, would it be possible to release a simplified or redacted version?

Feel free to reach out to me directly at mamarasulovsardor@gmail.com 

Thanks again

**Comment by Wertiz** [comment]
Replied [here](https://github.com/grip-unina/poi-forensics/issues/3#issuecomment-1867590124)
